### PR TITLE
Expand postings eagerly

### PR DESCRIPTION
**Pull request by gouthamve**
See: https://github.com/prometheus/tsdb/pull/240#issuecomment-363794548

---
This change is [Reviewable](https://reviewable.io/reviews/prometheus/tsdb/278)

### CODE REVIEW

**Comment by fabxc** [comment]
On hold until the storage is back in stable state.

**Comment by krasi-georgiev** [comment]
@gouthamve shall I review, is this still relevant?

**Comment by brian-brazil** [comment]
I don't expect this to make any difference

**Comment by krasi-georgiev** [comment]
Results from the promql bench test are in https://github.com/prometheus/tsdb/pull/467#issuecomment-445907227

Anyway closing this one as https://github.com/prometheus/tsdb/pull/467 includes these changes so lets continue the discussions there

**Pull request closed without merging**
