### PR TITLE
Use Go modules

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by brancz** [comment]
lgtm :+1:

**Comment by krasi-georgiev** [comment]
wow the common makefile is starting to grow quite a bit. 

Will these extra conditional checks be removed once the go modules are officially supported by default?

**Comment by simonpasquier** [comment]
> Will these extra conditional checks be removed once the go modules are officially supported by default?

Sure but because of projects such as [client_golang](https://github.com/prometheus/client_golang/) that need to support older Go versions, it will take some time to get there.

**Comment by simonpasquier** [comment]
The failing tests are due to Travis, nothing to do with this patch.

> Is there any other project apart from client_golang that required this? If not than maybe just have a custom Makefile for that project only. No need to pollute everything else because of a single project.

IMO it defeats the purpose of having a common Makefile. Part of the changes in this patch aren't related to Go modules (see https://github.com/prometheus/prometheus/pull/4843).

**Comment by krasi-georgiev** [comment]
that is strange 
I re-run the test and it is failing.

**Comment by simonpasquier** [comment]
It is a different failure now. Checking.

**Comment by simonpasquier** [comment]
Since https://github.com/prometheus/tsdb/pull/412 `github.com/prometheus/client_model` is a direct dependency (while it was indirect before): this is why Travis was failing.

**Comment by krasi-georgiev** [comment]
yep that makes sense. 
Thanks.

Still a bit concerned of how quickly the Makefile.common grew in size and logic and I hope it doesn't go out of control for covering too many edge cases.

lgtm

**Pull request merged**
