### PR TITLE
fix for missing overlapping blocks from selectOverlappingDirs

### PR DESCRIPTION
**Pull request by krasi-georgiev**
fixes https://github.com/prometheus/tsdb/issues/554
Signed-off-by: Krasi Georgiev <kgeorgie@redhat.com>

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
cc  @naivewong

**Comment by bwplotka** [comment]
This is needed once https://github.com/prometheus/tsdb/pull/560 is merged?

**Comment by krasi-georgiev** [comment]
nope I opened this PR first, but than @naivewong came up with another solution so it is one or the other.

**Comment by krasi-georgiev** [comment]
The other PR has advanced more so closing this one for now.

**Pull request closed without merging**
