### PR TITLE
add maintainers file

### PR DESCRIPTION
**Pull request by krasi-georgiev**
fixes https://github.com/prometheus/tsdb/issues/403

@fabxc not sure if you wanted to be on that list as well so let me know and will add you.

Signed-off-by: Krasi Georgiev <kgeorgie@redhat.com>

### CODE REVIEW

**Comment by beorn7** [comment]
:+1:

**Comment by RichiH** [comment]
That being said, having a dot trail the Twitter handle makes my OCD scream in pain and confusion.

**Comment by krasi-georgiev** [comment]
Are you refering to @krasi-georgiev. and @gouthamve. ? I thought these are github handles.

**Comment by RichiH** [comment]
Either way, I would kill the trailing dot.

**Comment by krasi-georgiev** [comment]
updated.

**Comment by gouthamve** [comment]
LGTM, but I'd like @fabxc to chime in before we merge this.

**Comment by krasi-georgiev** [comment]
merged it to clear the queue. If Fabian has any notes/objections will open a new PR.

**Pull request merged**
