### PR TITLE
Update head time when reading wal

### PR DESCRIPTION
**Pull request by krasi-georgiev**
When reading he WAL head mint and maxt didn't get updated.

@gouthamve found this bug I am just submitting it on his behalf.

### CODE REVIEW

**Comment by fabxc** [comment]
Those changes probably conflict with #332. Coincidentally I ran into the same bug when doing it and already fixed it there along with other changes: https://github.com/prometheus/tsdb/pull/332/files#diff-0ced3454d447442a96a77b33ebe87300R233

**Comment by krasi-georgiev** [comment]
@fabxc yes I noticed , but it seems that the update for the head mint is still missing?

**Comment by krasi-georgiev** [comment]
@fabxc not causing any issues so far. I wanted to keep it just as reminder after you merge the new wall.
if you have it in your TODO list feel free to close. just don't forget to update the tests as well.

**Comment by krasi-georgiev** [comment]
superseded by #339

**Pull request closed without merging**
