### PR TITLE
Add block ULID to index reader errors

### PR DESCRIPTION
**Pull request by Gouthamve**
Not happy with this PR and is unlikely to be merged but this patch would unblock people who have issues with corrupt indexes.

@SuperQ

---
This change is [Reviewable](https://reviewable.io/reviews/prometheus/tsdb/261)

### CODE REVIEW

**Comment by fabxc** [comment]
We don't have the ULID available at the call sites?

Maybe we could at least exchange this for a wrapper `IndexReader` in the root package that attaches these rather than leaking this all across the code?

**Comment by Gouthamve** [comment]
Yeah, that's better. I was thinking of making the querier do it, but couldn't find the right abstraction, I guess :) Let me do this.

**Comment by Gouthamve** [comment]
@fabxc How about now?

**Comment by fabxc** [comment]
👍

**Pull request merged**
