### PR TITLE
Prevent creation of block dirs with zero samples

### PR DESCRIPTION
**Pull request by nipuntalukdar**

### CODE REVIEW

**Comment by nipuntalukdar** [comment]
Made a small change that will prevent creation of block dirs with zero samples during compaction.

**Comment by Gouthamve** [comment]
Instead of this can we return super early? Like right after the defer?

**Comment by nipuntalukdar** [comment]
I think we cannot return early because before deferred function is called, the tmp directories might have been created. Also, the error will be very infrequent and hence shouldn't have any impact by allowing proper cleanup flow.

**Comment by Gouthamve** [comment]
Oh no. https://github.com/prometheus/tsdb/pull/245/files#diff-43297cfd6441b52c54c50d646a564339R419 this is where we create the tmp directory. We removeAll before just to make sure but there should be no such temp dir.

**Comment by krasi-georgiev** [comment]
superseded by: https://github.com/prometheus/tsdb/pull/374

**Pull request closed without merging**
