### PR TITLE
[WIP] add a rwmutex to fix the race in xorAppender

### LINKED ISSUE #284: Data race between chunkenc.(*xorAppender).Append() and chunkenc.(*XORChunk).NumSamples()
Found at 494acd3 by running:

```
go run -race cmd/tsdb/main.go bench write --metrics 1000000 testdata/20kseries.json
```

Go version: `go version go1.10 darwin/amd64`

`chunkenc.(*XORChunk).NumSamples()` is reading from the `bstream` byte slice (via `binary.BigEndian.Uint16()`) at the same time that `chunkenc.(*xorAppender).Append()` is writing to the same buffer (via `binary.BigEndian.PutUint16()`).

Stacktrace:

```
WARNING: DATA RACE
Write at 0x00c4229a9c00 by goroutine 29:
  github.com/prometheus/tsdb/chunkenc.(*xorAppender).Append()
      /usr/local/Cellar/go/1.10/libexec/src/encoding/binary/binary.go:106 +0x68b
  github.com/prometheus/tsdb.(*memSeries).append()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:1225 +0x18a
  github.com/prometheus/tsdb.(*headAppender).Commit()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:538 +0x288
  github.com/prometheus/tsdb.dbAppender.Commit()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:348 +0x42
  github.com/prometheus/tsdb.(*dbAppender).Commit()
      <autogenerated>:1 +0x7a
  main.(*writeBenchmark).ingestScrapesShard()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:234 +0x851
  main.(*writeBenchmark).ingestScrapes.func1()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:169 +0xa8

Previous read at 0x00c4229a9c00 by goroutine 23:
  github.com/prometheus/tsdb/chunkenc.(*XORChunk).NumSamples()
      /usr/local/Cellar/go/1.10/libexec/src/encoding/binary/binary.go:101 +0x97
  github.com/prometheus/tsdb.(*safeChunk).NumSamples()
      <autogenerated>:1 +0x57
  github.com/prometheus/tsdb.(*instrumentedChunkWriter).WriteChunks()
      /Users/matt/go/src/github.com/prometheus/tsdb/compact.go:378 +0x13a
  github.com/prometheus/tsdb.(*LeveledCompactor).populateBlock()
      /Users/matt/go/src/github.com/prometheus/tsdb/compact.go:578 +0x1539
  github.com/prometheus/tsdb.(*LeveledCompactor).write()
      /Users/matt/go/src/github.com/prometheus/tsdb/compact.go:435 +0x7bd
  github.com/prometheus/tsdb.(*LeveledCompactor).Write()
      /Users/matt/go/src/github.com/prometheus/tsdb/compact.go:362 +0x45f
  github.com/prometheus/tsdb.(*DB).compact()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:390 +0x45f
  github.com/prometheus/tsdb.(*DB).run()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:279 +0x38c

Goroutine 29 (running) created at:
  main.(*writeBenchmark).ingestScrapes()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:168 +0x186
  main.(*writeBenchmark).run.func2()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:133 +0xaf
  main.measureTime()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:300 +0x130
  main.(*writeBenchmark).run()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:131 +0x6f7
  main.main()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:58 +0x129a

Goroutine 23 (running) created at:
  github.com/prometheus/tsdb.Open()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:243 +0x8cd
  main.(*writeBenchmark).run()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:104 +0x4e6
  main.main()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:58 +0x129a
```

...and related:

```
WARNING: DATA RACE
Write at 0x00c421f1b660 by goroutine 71:
  github.com/prometheus/tsdb/chunkenc.(*bstream).writeBits()
      /Users/matt/go/src/github.com/prometheus/tsdb/chunkenc/bstream.go:103 +0x223
  github.com/prometheus/tsdb/chunkenc.(*xorAppender).writeVDelta()
      /Users/matt/go/src/github.com/prometheus/tsdb/chunkenc/xor.go:207 +0x9b2
  github.com/prometheus/tsdb/chunkenc.(*xorAppender).Append()
      /Users/matt/go/src/github.com/prometheus/tsdb/chunkenc/xor.go:175 +0x853
  github.com/prometheus/tsdb.(*memSeries).append()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:1225 +0x18a
  github.com/prometheus/tsdb.(*headAppender).Commit()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:538 +0x288
  github.com/prometheus/tsdb.dbAppender.Commit()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:348 +0x42
  github.com/prometheus/tsdb.(*dbAppender).Commit()
      <autogenerated>:1 +0x7a
  main.(*writeBenchmark).ingestScrapesShard()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:234 +0x851
  main.(*writeBenchmark).ingestScrapes.func1()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:169 +0xa8

Previous read at 0x00c421f1b660 by goroutine 23:
  github.com/prometheus/tsdb/chunkenc.(*XORChunk).Bytes()
      /Users/matt/go/src/github.com/prometheus/tsdb/chunkenc/bstream.go:67 +0x52
  github.com/prometheus/tsdb.(*safeChunk).Bytes()
      <autogenerated>:1 +0x5f
  github.com/prometheus/tsdb/chunks.(*Writer).WriteChunks()
      /Users/matt/go/src/github.com/prometheus/tsdb/chunks/chunks.go:201 +0xf4
  github.com/prometheus/tsdb.(*instrumentedChunkWriter).WriteChunks()
      /Users/matt/go/src/github.com/prometheus/tsdb/compact.go:381 +0x240
  github.com/prometheus/tsdb.(*LeveledCompactor).populateBlock()
      /Users/matt/go/src/github.com/prometheus/tsdb/compact.go:578 +0x1539
  github.com/prometheus/tsdb.(*LeveledCompactor).write()
      /Users/matt/go/src/github.com/prometheus/tsdb/compact.go:435 +0x7bd
  github.com/prometheus/tsdb.(*LeveledCompactor).Write()
      /Users/matt/go/src/github.com/prometheus/tsdb/compact.go:362 +0x45f
  github.com/prometheus/tsdb.(*DB).compact()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:390 +0x45f
  github.com/prometheus/tsdb.(*DB).run()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:279 +0x38c

Goroutine 71 (running) created at:
  main.(*writeBenchmark).ingestScrapes()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:168 +0x186
  main.(*writeBenchmark).run.func2()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:133 +0xaf
  main.measureTime()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:300 +0x130
  main.(*writeBenchmark).run()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:131 +0x6f7
  main.main()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:58 +0x129a

Goroutine 23 (running) created at:
  github.com/prometheus/tsdb.Open()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:243 +0x8cd
  main.(*writeBenchmark).run()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:104 +0x4e6
  main.main()
      /Users/matt/go/src/github.com/mattbostock/tsdb/cmd/tsdb/main.go:58 +0x129a
```

### PR DESCRIPTION
**Pull request by krasi-georgiev**
attempt to fix #284

I couldn't replicate the race , but this change should fix the race. 
Only if....it didn't decrease the performance :-1: 
@Gouthamve , @fabxc I will keep digging, but do you think this should be possible without a mutex?
ping me on irc

Before mutex
>> completed stage=ingestScrapes duration=3m8.752500067s
 > total samples: 60000000
 > samples/sec: 317876.5471555682

After the mutex
>> completed stage=ingestScrapes duration=4m4.182568715s
 > total samples: 60000000
 > samples/sec: 245717.76789062202

### CODE REVIEW

**Comment by fabxc** [comment]
Thanks. A mutex is indeed suboptimal here. Have you tried to run it with a plain `Mutex`. That should already be a fair bit better.

One thing I noticed a while ago is that the BigEndian decoding of the first two bytes when we want to retrieve the number of samples actually accounts for a fair bit of CPU usage. Likely because we call it during ingestion quite often.
We might be better of just storing that value cached in an integer during appends and only write it into the first two bytes of our slice upon completion.

To say more, I'll have to take a closer look myself again tomorrow though.

**Comment by krasi-georgiev** [comment]
yep , much better.  I will continue digging.

>> completed stage=ingestScrapes duration=2m43.341499255s
 > total samples: 60000000
 > samples/sec: 367328.5151949328


>> completed stage=ingestScrapes duration=3m4.27498979s
 > total samples: 60000000
 > samples/sec: 325600.2951579569

**Comment by krasi-georgiev** [comment]
@fabxc yep the `NumSamples()` is easy, but the second one is mind blowing 

the chunk `Appender` writes to the bytes slice while the `ChunkWriter` reads from  the  same bytes slice so still brainstoriming how to solve without any blocking :face_with_head_bandage: 

https://github.com/prometheus/tsdb/blob/def6e5a57439cffe7b44a619c05bce4ac513a63e/chunks/chunks.go#L229 ( trigered by the compaction )

https://github.com/prometheus/tsdb/blob/def6e5a57439cffe7b44a619c05bce4ac513a63e/chunkenc/bstream.go#L94

**Comment by brian-brazil** [comment]
This doesn't seem right at all, an appender should only be written to from one thread. This is a critical path, we should avoid putting a mutex on it - the bug is elsewhere.

**Comment by krasi-georgiev** [comment]
the  report is a bit confusing as it only shows a single Goroutine 35 causing the race.


to replicate I had to change the `ingestScrapes` func as below and run:
`GORACE=history_size=7  go run -race cmd/tsdb/main.go bench write --metrics 1000000 testdata/20kseries.json`

```
func (b *writeBenchmark) ingestScrapes(lbls []labels.Labels, scrapeCount int) (uint64, error) {
	var mu sync.Mutex
	var total uint64

	for i := 0; i < scrapeCount; i += 100 {
		// var wg sync.WaitGroup
		lbls := lbls
		for len(lbls) > 0 {
			l := 1000
			if len(lbls) < 1000 {
				l = len(lbls)
			}
			batch := lbls[:l]
			lbls = lbls[l:]

			// wg.Add(1)
			// go func() {
			n, err := b.ingestScrapesShard(batch, 100, int64(timeDelta*i))
			if err != nil {
				// exitWithError(err)
				fmt.Println(" err", err)
			}
			mu.Lock()
			total += n
			mu.Unlock()
			// wg.Done()
			// }()
		}
		// wg.Wait()
	}
	fmt.Println("ingestion completed")

	return total, nil
}
```

here is the race log:

```
==================
WARNING: DATA RACE
Write at 0x00c424f67760 by main goroutine:
  github.com/prometheus/tsdb/chunkenc.(*xorAppender).Append()
      /home/krasi/src/github.com/prometheus/tsdb/chunkenc/bstream.go:93 +0x9d8
  github.com/prometheus/tsdb.(*memSeries).append()
      /home/krasi/src/github.com/prometheus/tsdb/head.go:1231 +0x17b
  github.com/prometheus/tsdb.(*headAppender).Commit()
      /home/krasi/src/github.com/prometheus/tsdb/head.go:537 +0x288
  github.com/prometheus/tsdb.dbAppender.Commit()
      /home/krasi/src/github.com/prometheus/tsdb/db.go:348 +0x42
  github.com/prometheus/tsdb.(*dbAppender).Commit()
      <autogenerated>:1 +0x7a
  main.(*writeBenchmark).ingestScrapesShard()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:234 +0x851
  main.(*writeBenchmark).ingestScrapes()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:169 +0x15c
  main.(*writeBenchmark).run.func2()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:133 +0xaf
  main.measureTime()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:300 +0x130
  main.(*writeBenchmark).run()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:131 +0x6f7
  main.main()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:58 +0x12b7

Previous read at 0x00c424f67760 by goroutine 35:
  github.com/prometheus/tsdb/chunkenc.(*XORChunk).Bytes()
      /home/krasi/src/github.com/prometheus/tsdb/chunkenc/xor.go:76 +0x4d
  github.com/prometheus/tsdb.(*safeChunk).Bytes()
      <autogenerated>:1 +0x5f
  github.com/prometheus/tsdb/chunks.(*Writer).WriteChunks()
      /home/krasi/src/github.com/prometheus/tsdb/chunks/chunks.go:229 +0x431
  github.com/prometheus/tsdb.(*instrumentedChunkWriter).WriteChunks()
      /home/krasi/src/github.com/prometheus/tsdb/compact.go:407 +0x242
  github.com/prometheus/tsdb.(*LeveledCompactor).populateBlock()
      /home/krasi/src/github.com/prometheus/tsdb/compact.go:603 +0x1555
  github.com/prometheus/tsdb.(*LeveledCompactor).write()
      /home/krasi/src/github.com/prometheus/tsdb/compact.go:459 +0x465
  github.com/prometheus/tsdb.(*LeveledCompactor).Write()
      /home/krasi/src/github.com/prometheus/tsdb/compact.go:382 +0x472
  github.com/prometheus/tsdb.(*DB).compact()
      /home/krasi/src/github.com/prometheus/tsdb/db.go:390 +0x45f
  github.com/prometheus/tsdb.(*DB).run()
      /home/krasi/src/github.com/prometheus/tsdb/db.go:279 +0x38c

Goroutine 35 (running) created at:
  github.com/prometheus/tsdb.Open()
      /home/krasi/src/github.com/prometheus/tsdb/db.go:243 +0x8cd
  main.(*writeBenchmark).run()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:104 +0x4e6
  main.main()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:58 +0x12b7
==================
==================
WARNING: DATA RACE
Write at 0x00c421c88e92 by main goroutine:
  github.com/prometheus/tsdb/chunkenc.(*xorAppender).writeVDelta()
      /home/krasi/src/github.com/prometheus/tsdb/chunkenc/bstream.go:100 +0x378
  github.com/prometheus/tsdb/chunkenc.(*xorAppender).Append()
      /home/krasi/src/github.com/prometheus/tsdb/chunkenc/xor.go:181 +0x754
  github.com/prometheus/tsdb.(*memSeries).append()
      /home/krasi/src/github.com/prometheus/tsdb/head.go:1231 +0x17b
  github.com/prometheus/tsdb.(*headAppender).Commit()
      /home/krasi/src/github.com/prometheus/tsdb/head.go:537 +0x288
  github.com/prometheus/tsdb.dbAppender.Commit()
      /home/krasi/src/github.com/prometheus/tsdb/db.go:348 +0x42
  github.com/prometheus/tsdb.(*dbAppender).Commit()
      <autogenerated>:1 +0x7a
  main.(*writeBenchmark).ingestScrapesShard()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:234 +0x851
  main.(*writeBenchmark).ingestScrapes()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:169 +0x15c
  main.(*writeBenchmark).run.func2()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:133 +0xaf
  main.measureTime()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:300 +0x130
  main.(*writeBenchmark).run()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:131 +0x6f7
  main.main()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:58 +0x12b7

Previous read at 0x00c421c88e92 by goroutine 35:
  runtime.slicecopy()
      /usr/local/go/src/runtime/slice.go:192 +0x0
  bufio.(*Writer).Write()
      /usr/local/go/src/bufio/bufio.go:617 +0x3f4
  github.com/prometheus/tsdb/chunks.(*Writer).write()
      /home/krasi/src/github.com/prometheus/tsdb/chunks/chunks.go:190 +0x76
  github.com/prometheus/tsdb/chunks.(*Writer).WriteChunks()
      /home/krasi/src/github.com/prometheus/tsdb/chunks/chunks.go:229 +0x442
  github.com/prometheus/tsdb.(*instrumentedChunkWriter).WriteChunks()
      /home/krasi/src/github.com/prometheus/tsdb/compact.go:407 +0x242
  github.com/prometheus/tsdb.(*LeveledCompactor).populateBlock()
      /home/krasi/src/github.com/prometheus/tsdb/compact.go:603 +0x1555
  github.com/prometheus/tsdb.(*LeveledCompactor).write()
      /home/krasi/src/github.com/prometheus/tsdb/compact.go:459 +0x465
  github.com/prometheus/tsdb.(*LeveledCompactor).Write()
      /home/krasi/src/github.com/prometheus/tsdb/compact.go:382 +0x472
  github.com/prometheus/tsdb.(*DB).compact()
      /home/krasi/src/github.com/prometheus/tsdb/db.go:390 +0x45f
  github.com/prometheus/tsdb.(*DB).run()
      /home/krasi/src/github.com/prometheus/tsdb/db.go:279 +0x38c

Goroutine 35 (running) created at:
  github.com/prometheus/tsdb.Open()
      /home/krasi/src/github.com/prometheus/tsdb/db.go:243 +0x8cd
  main.(*writeBenchmark).run()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:104 +0x4e6
  main.main()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:58 +0x12b7
==================
==================
WARNING: DATA RACE
Write at 0x00c426afdbe0 by main goroutine:
  github.com/prometheus/tsdb/chunkenc.(*xorAppender).writeVDelta()
      /home/krasi/src/github.com/prometheus/tsdb/chunkenc/bstream.go:93 +0xa39
  github.com/prometheus/tsdb/chunkenc.(*xorAppender).Append()
      /home/krasi/src/github.com/prometheus/tsdb/chunkenc/xor.go:181 +0x754
  github.com/prometheus/tsdb.(*memSeries).append()
      /home/krasi/src/github.com/prometheus/tsdb/head.go:1231 +0x17b
  github.com/prometheus/tsdb.(*headAppender).Commit()
      /home/krasi/src/github.com/prometheus/tsdb/head.go:537 +0x288
  github.com/prometheus/tsdb.dbAppender.Commit()
      /home/krasi/src/github.com/prometheus/tsdb/db.go:348 +0x42
  github.com/prometheus/tsdb.(*dbAppender).Commit()
      <autogenerated>:1 +0x7a
  main.(*writeBenchmark).ingestScrapesShard()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:234 +0x851
  main.(*writeBenchmark).ingestScrapes()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:169 +0x15c
  main.(*writeBenchmark).run.func2()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:133 +0xaf
  main.measureTime()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:300 +0x130
  main.(*writeBenchmark).run()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:131 +0x6f7
  main.main()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:58 +0x12b7

Previous read at 0x00c426afdbe0 by goroutine 35:
  github.com/prometheus/tsdb/chunkenc.(*XORChunk).Bytes()
      /home/krasi/src/github.com/prometheus/tsdb/chunkenc/xor.go:76 +0x4d
  github.com/prometheus/tsdb.(*safeChunk).Bytes()
      <autogenerated>:1 +0x5f
  github.com/prometheus/tsdb/chunks.(*Writer).WriteChunks()
      /home/krasi/src/github.com/prometheus/tsdb/chunks/chunks.go:229 +0x431
  github.com/prometheus/tsdb.(*instrumentedChunkWriter).WriteChunks()
      /home/krasi/src/github.com/prometheus/tsdb/compact.go:407 +0x242
  github.com/prometheus/tsdb.(*LeveledCompactor).populateBlock()
      /home/krasi/src/github.com/prometheus/tsdb/compact.go:603 +0x1555
  github.com/prometheus/tsdb.(*LeveledCompactor).write()
      /home/krasi/src/github.com/prometheus/tsdb/compact.go:459 +0x465
  github.com/prometheus/tsdb.(*LeveledCompactor).Write()
      /home/krasi/src/github.com/prometheus/tsdb/compact.go:382 +0x472
  github.com/prometheus/tsdb.(*DB).compact()
      /home/krasi/src/github.com/prometheus/tsdb/db.go:390 +0x45f
  github.com/prometheus/tsdb.(*DB).run()
      /home/krasi/src/github.com/prometheus/tsdb/db.go:279 +0x38c

Goroutine 35 (running) created at:
  github.com/prometheus/tsdb.Open()
      /home/krasi/src/github.com/prometheus/tsdb/db.go:243 +0x8cd
  main.(*writeBenchmark).run()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:104 +0x4e6
  main.main()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:58 +0x12b7
==================
==================
WARNING: DATA RACE
Write at 0x00c424f599e0 by main goroutine:
  github.com/prometheus/tsdb/chunkenc.(*bstream).writeBits()
      /home/krasi/src/github.com/prometheus/tsdb/chunkenc/bstream.go:117 +0x223
  github.com/prometheus/tsdb/chunkenc.(*xorAppender).writeVDelta()
      /home/krasi/src/github.com/prometheus/tsdb/chunkenc/xor.go:215 +0x9b2
  github.com/prometheus/tsdb/chunkenc.(*xorAppender).Append()
      /home/krasi/src/github.com/prometheus/tsdb/chunkenc/xor.go:181 +0x754
  github.com/prometheus/tsdb.(*memSeries).append()
      /home/krasi/src/github.com/prometheus/tsdb/head.go:1231 +0x17b
  github.com/prometheus/tsdb.(*headAppender).Commit()
      /home/krasi/src/github.com/prometheus/tsdb/head.go:537 +0x288
  github.com/prometheus/tsdb.dbAppender.Commit()
      /home/krasi/src/github.com/prometheus/tsdb/db.go:348 +0x42
  github.com/prometheus/tsdb.(*dbAppender).Commit()
      <autogenerated>:1 +0x7a
  main.(*writeBenchmark).ingestScrapesShard()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:234 +0x851
  main.(*writeBenchmark).ingestScrapes()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:169 +0x15c
  main.(*writeBenchmark).run.func2()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:133 +0xaf
  main.measureTime()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:300 +0x130
  main.(*writeBenchmark).run()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:131 +0x6f7
  main.main()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:58 +0x12b7

Previous read at 0x00c424f599e0 by goroutine 35:
  github.com/prometheus/tsdb/chunkenc.(*XORChunk).Bytes()
      /home/krasi/src/github.com/prometheus/tsdb/chunkenc/xor.go:76 +0x4d
  github.com/prometheus/tsdb.(*safeChunk).Bytes()
      <autogenerated>:1 +0x5f
  github.com/prometheus/tsdb/chunks.(*Writer).WriteChunks()
      /home/krasi/src/github.com/prometheus/tsdb/chunks/chunks.go:229 +0x431
  github.com/prometheus/tsdb.(*instrumentedChunkWriter).WriteChunks()
      /home/krasi/src/github.com/prometheus/tsdb/compact.go:407 +0x242
  github.com/prometheus/tsdb.(*LeveledCompactor).populateBlock()
      /home/krasi/src/github.com/prometheus/tsdb/compact.go:603 +0x1555
  github.com/prometheus/tsdb.(*LeveledCompactor).write()
      /home/krasi/src/github.com/prometheus/tsdb/compact.go:459 +0x465
  github.com/prometheus/tsdb.(*LeveledCompactor).Write()
      /home/krasi/src/github.com/prometheus/tsdb/compact.go:382 +0x472
  github.com/prometheus/tsdb.(*DB).compact()
      /home/krasi/src/github.com/prometheus/tsdb/db.go:390 +0x45f
  github.com/prometheus/tsdb.(*DB).run()
      /home/krasi/src/github.com/prometheus/tsdb/db.go:279 +0x38c

Goroutine 35 (running) created at:
  github.com/prometheus/tsdb.Open()
      /home/krasi/src/github.com/prometheus/tsdb/db.go:243 +0x8cd
  main.(*writeBenchmark).run()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:104 +0x4e6
  main.main()
      /home/krasi/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:58 +0x12b7
==================
```

**Comment by gouthamve** [comment]
Yep, the bug seems to be elsewhere. In the case above, we are compacting the chunks that are still being written to! Now that shouldn't happen at all.

**Comment by krasi-georgiev** [comment]
I will have a look again.  But anyone has any ideas?

**Comment by krasi-georgiev** [comment]
I think I figured it, will update the PR.

**Pull request closed without merging**
