### PR TITLE
Rename metrics from prometheus_tsdb to tsdb_

### PR DESCRIPTION
**Pull request by roidelapluie**
The prefix prometheus_ will only be added when used within Prometheus.

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
see https://github.com/prometheus/prometheus/pull/5328

**Comment by brian-brazil** [comment]
These are prometheus_tsdb metrics, not prometheus tsdb metrics - so this is fine. Just tsdb would be ambiguous as there's many many tsdbs out there.

**Comment by roidelapluie** [comment]
ok. Is is still worth it to refactor to use WrapRegistererWithPrefix?

**Comment by roidelapluie** [comment]
What I find really confusing is that there are prometheus_tsdb_ metrics coming from TSDB and other ones from prometheus, which sounds like namespace violation.

**Comment by brian-brazil** [comment]
Yeah, that clash is a bit messy.

**Pull request closed without merging**
