### PR TITLE
chunks: close all opened MmapFiles on NewDirReader error path

### PR DESCRIPTION
**Pull request by pborzenkov**

### CODE REVIEW

**Comment by pborzenkov** [comment]
CI failed on go1.10/macOS:

```
>> getting dependencies
go get  -t ./...
# golang.org/x/sys/unix
../../../golang.org/x/sys/unix/zsyscall_darwin_amd64.1_11.go:687:22: undefined: SYS_CLOCK_GETTIME
make: *** [common-deps] Error 2
```

**Comment by krasi-georgiev** [comment]
I wouldn't worry about that since we won't support 1.10 anyway.

Wondering whether a test here would be useful. 
Something like : 
open a dir with a single corrupted file to trigger the error.
Next try to delete all files. Without this fix the test would fail under windows with an error that the file is still open.

**Comment by pborzenkov** [comment]
@krasi-georgiev Hmm, the problem is that we need to trigger an error in OpenMmapFile, which doesn't perform any validation at all. So either some kind of fault injection is required, or an OpenMmapFile mock.

**Comment by krasi-georgiev** [comment]
Had a quick look and don't have any good ideas either so lets leave it as is for now.

**Comment by krasi-georgiev** [comment]
Thanks for the bugfix!

**Pull request merged**
