### PR TITLE
tsdb cli command to convert the wal into a block

### PR DESCRIPTION
**Pull request by krasi-georgiev**
closes https://github.com/prometheus/tsdb/issues/346
Signed-off-by: Krasi Georgiev <kgeorgie@redhat.com>

### CODE REVIEW

**Comment by brancz** [comment]
Can you elaborate on in which regard this is work-in-progress? Does it need tests, does it need testing with real WALs?

**Comment by krasi-georgiev** [comment]
it is WIP because we don't know yet whether it will solve the actual problem.
Once you confirm that it solves it I will tidy up and see what/if else is needed.

**Comment by brancz** [comment]
ack, sounds good to me :)

**Comment by krasi-georgiev** [comment]
refactored to require less changes in the tsdb internals. 

Now it takes the mint for the new block from the wal  from the maxt of the last block in the db.

**Comment by krasi-georgiev** [comment]
will reopen if/when needed.

**Pull request closed without merging**
