### PR TITLE
add a metric for the last time a sample was logged to the WAL

### PR DESCRIPTION
**Pull request by cstyan**
As part of changing Prometheus' remote write path to read data from the WAL rather than gathering it from scrapes, it will be useful to compare the last time data was written to the WAL vs. the last time each remote write config. successfully sent samples to it's remote storage.

Signed-off-by: Callum Styan <callumstyan@gmail.com>

### CODE REVIEW

**Comment by cstyan** [comment]
@gouthamve @krasi-georgiev 
cc: @fabxc

**Comment by krasi-georgiev** [comment]
I think checkpointing was implemented to solve this problem, no?

**Comment by krasi-georgiev** [comment]
based on the  discussion in https://github.com/prometheus/tsdb/issues/395 I think this is best to instrument in Prometheus itself so that you can also add the metric name sec/milsec etc.

**Comment by krasi-georgiev** [comment]
while you are at it can also add the mint to Prometheus itself so we can close https://github.com/prometheus/tsdb/issues/395 as well.

**Comment by cstyan** [comment]
We don't really have the same issue as #395, Gauge `SetToCurrentTime` is the timestamp in seconds. Either way, I've opened a PR https://github.com/prometheus/prometheus/pull/4750

**Comment by krasi-georgiev** [comment]
will continue tracking in https://github.com/prometheus/prometheus/pull/4750

**Pull request closed without merging**
