### PR TITLE
Add vendoring.

### PR DESCRIPTION
**Pull request by brian-brazil**
This fixes CI breaking due to a dependency on the dev-2.0
branch of Prometheus.

### CODE REVIEW

**Comment by brian-brazil** [comment]
@fabxc Looks like that was the only thing broken with the CI.

**Comment by grobie** [comment]
It's not common practice to vendor dependencies of libraries.

**Comment by brian-brazil** [comment]
Do you have a suggestion for another way to get the CI passing while dev-2.0 is not master?

**Comment by grobie** [comment]
AFAIK only github.com/prometheus/prometheus/pkg/labels needs to be in
master, we could merge this already.

**Comment by fabxc** [comment]
Yea, packporting pkg/ into master for the transition is the sanest approach

**Comment by brian-brazil** [comment]
https://github.com/prometheus/prometheus/pull/2646

**Pull request closed without merging**
