### PR TITLE
Release v0.3.0

### PR DESCRIPTION
**Pull request by krasi-georgiev**
@gouthamve 	what do you think about this changelog format and wording? 

I am trying to write it so that searching through the changelog file with keywords would also give context about the different changes. This way if a behaviour is removed at some point can also deprecate/refactor the corresponding API

### CODE REVIEW

**Comment by brian-brazil** [comment]
I think we should stick with the project's standard format. If someone needs this level of detail, they can always look at the commit history.

**Comment by krasi-georgiev** [comment]
for a library it might be a bit different, consumers might want a quick overview of what has changed and what changes they might need in their code to update from one version to another etc. 
@gouthamve 	thoughts? since you are using tsdb as a library, would something like this be useful?

**Comment by brian-brazil** [comment]
We follow the usual format in our other libraries, and they're more user facing than this one.

**Comment by krasi-georgiev** [comment]
simplified.

**Comment by brian-brazil** [comment]
:+1:

**Pull request merged**
