### PR TITLE
Do not output chunks that will be outside of the current max head time in future

### PR DESCRIPTION
**Pull request by work-chausat**

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
Thanks for the PR.
does this fix a bug and what are the steps to reproduce it?

we should also add a test if it fixes a bug.

**Comment by work-chausat** [comment]
OK, i modified the TestDB_Snapshot to show what i said.

func TestDB_Snapshot(t *testing.T) {
	db, close := openTestDB(t, nil)
	defer close()

	mint := int64(1414141414000)

	app := db.Appender()


	for i := 0; i < 1000; i++ {
		_, err := app.Add(labels.FromStrings("foo", "bar"+strconv.Itoa(i)), mint+int64(i), 1.0)
		testutil.Ok(t, err)
	}

	testutil.Ok(t, app.Commit())
	testutil.Ok(t, app.Rollback())


	// append data
	go func() {
		app2 := db.Appender()
		for i := 1001; i < 100000; i++ {
			_, err := app2.Add(labels.FromStrings("foo", "bar"+strconv.Itoa(i)), mint+int64(i), 1.0)
			testutil.Ok(t, err)

			if i%1000 ==0{
				testutil.Ok(t, app2.Commit())
				testutil.Ok(t, app2.Rollback())
			}
		}


	}()

	// create snapshot
	snap, err := ioutil.TempDir("", "snap")
	testutil.Ok(t, err)

	defer os.RemoveAll(snap)
	testutil.Ok(t, db.Snapshot(snap, true))
	testutil.Ok(t, db.Close())

	// reopen DB from snapshot
	db, err = Open(snap, nil, nil, nil)
	testutil.Ok(t, err)
	defer db.Close()

	querier, err := db.Querier(mint, mint+1000)
	testutil.Ok(t, err)
	defer querier.Close()

	// sum values
	seriesSet, err := querier.Select(labels.NewPrefixMatcher("foo", "bar"))
	testutil.Ok(t, err)

	sum := 0.0
	for seriesSet.Next() {
		series := seriesSet.At().Iterator()
		for series.Next() {
			_, v := series.At()
			sum += v
		}
		testutil.Ok(t, series.Err())
	}
	testutil.Ok(t, seriesSet.Err())
	testutil.Equals(t, sum, 1000.0)
}

db_test.go:406: unexpected error: snapshot head block: write compaction: add series: symbol entry for "bar3338" does not exist

--- FAIL: TestDB_Snapshot (0.09s)
FAIL

after using &rangeHead, the error disappeared.

**Comment by work-chausat** [comment]
You also can use this version TestDB_Snapshot for test.


```
func TestDB_Snapshot(t *testing.T) {
	db, close := openTestDB(t, nil)
	defer close()

	mint := int64(1414141414000)

	app := db.Appender()


	for i := 0; i < 1000; i++ {
		_, err := app.Add(labels.FromStrings("foo", "bar"+strconv.Itoa(i)), mint+int64(i), 1.0)
		testutil.Ok(t, err)
	}

	testutil.Ok(t, app.Commit())
	testutil.Ok(t, app.Rollback())


	// append data
	go func() {
		app2 := db.Appender()
		for i := 1001; i < 3000; i++ {
			_, err := app2.Add(labels.FromStrings("foo", "bar"+strconv.Itoa(i)), mint+int64(i), 1.0)
			testutil.Ok(t, err)

			if i%1000 ==0{
				testutil.Ok(t, app2.Commit())
				testutil.Ok(t, app2.Rollback())
			}
		}


	}()

	// create snapshot
	snap, err := ioutil.TempDir("", "snap")
	testutil.Ok(t, err)

	defer os.RemoveAll(snap)
	testutil.Ok(t, db.Snapshot(snap, true))
	testutil.Ok(t, db.Close())

	// reopen DB from snapshot
	db, err = Open(snap, nil, nil, nil)

	testutil.Ok(t, err)
	defer db.Close()

	snapShotMaxTime := db.blocks[0].meta.MaxTime
	querier, err := db.Querier(snapShotMaxTime, snapShotMaxTime+500)
	testutil.Ok(t, err)
	defer querier.Close()

	// sum values
	seriesSet, err := querier.Select(labels.NewPrefixMatcher("foo", "bar"))
	testutil.Ok(t, err)

	sum := 0.0
	for seriesSet.Next() {
		series := seriesSet.At().Iterator()
		for series.Next() {
			_, v := series.At()
			sum += v
		}
		testutil.Ok(t, series.Err())
	}
	testutil.Ok(t, seriesSet.Err())
	testutil.Equals(t, sum, 0)
}
```

**Comment by krasi-georgiev** [comment]
> There is already #339 that addresses the issue the head initialisation so lets focus this one on fixing the Snapshoting.

**Comment by work-chausat** [comment]
@krasi-georgiev I saw. I think there are two problems, one is about output head to chunks, the other is about the head initialisation.

**Comment by krasi-georgiev** [comment]
yes, and the other one is already addresses in the PR I linked.

**Comment by work-chausat** [comment]
yes, the problem about the head initialisation is already addressed in the PR.

**Comment by krasi-georgiev** [comment]
Why did you close it? we still need the other changes. I meant just to remove the Head code changes.

**Pull request closed without merging**
