### PR TITLE
Add CircleCI releases

### PR DESCRIPTION
**Pull request by SuperQ**
Add CircleCI + Promu to release cmd/tsdb.

Closes: https://github.com/prometheus/tsdb/issues/484

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
since we use travis for the tests could we use to for the build as well?

**Comment by SuperQ** [comment]
Possibly, but we're using circleci for builds everywhere else. Picking a single CI is already a topic of discussion.

**Comment by krasi-georgiev** [comment]
yeah I know and I think the final opinion of @simonpasquier was to slowly migrate to travis. I think the build here is pretty small so maybe try it travis and if it ends up being a pain will use circle again but only for the builds. no need to run the same tests with travis and circle.

**Comment by SuperQ** [comment]
Ok, I guess we need to learn how to use multiple jobs/releases, remote docker, etc in Travis.

**Comment by krasi-georgiev** [comment]
seems that the circle build is triggered for all PRs and it fails as it doesn't find any config. Maybe enabled somewhere globally?

**Comment by SuperQ** [comment]
It's a GitHub integration, I will remove it.

**Pull request closed without merging**
