### PR TITLE
 NumSeries() method for BlockReader interface

### PR DESCRIPTION
**Pull request by codesome**
This is a broken down piece of  #627 and is required by #627.

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
the ReadOnly PR exposes the meta for the block and would cover your case as well.
https://github.com/prometheus/tsdb/pull/588

I was waiting for one final review, but if no one replies will merge in 1-2 days.

**Comment by codesome** [comment]
#588 doesn't give `NumSeries` for head. So either a part of this PR would be needed or the Meta returned by Head needs to expose `NumSeries`.

**Comment by krasi-georgiev** [comment]
yes I meant to add the NumSeries the read only db PR.

**Comment by codesome** [comment]
Closing this as its available as `.Meta().NumSeries` after https://github.com/prometheus/tsdb/pull/588 was merged.

**Pull request closed without merging**
