### PR TITLE
Fixs annotation spelling error

### PR DESCRIPTION
**Pull request by JoeWrightss**
Fix annotation typo "proecedure" to "procedure" in [wal_test.go](https://github.com/prometheus/tsdb/compare/master...JoeWrightss:patch-4?expand=1#diff-7a895460ba897c8893d5bd0110feaaca) at line 439.

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
I see that you did few similar typo fixes. Are you reading through the code?

If you don't mind I will keep this PR open for a while so if find more spelling mistakes just add the fixes here instead of opening a new PR for each typo.

**Comment by JoeWrightss** [comment]
I don't mind😊.

**Comment by krasi-georgiev** [comment]
Thanks, keep digging for more fixes and ping me when you accumulate enough changes.

**Comment by JoeWrightss** [comment]
I found that these problems no longer exist, so close this PR?

**Comment by brian-brazil** [comment]
If the PR is no longer relevant, you can close it.

**Pull request closed without merging**
