### PR TITLE
update copyright headers

### PR DESCRIPTION
**Pull request by krasi-georgiev**
Signed-off-by: Krasi Georgiev <kgeorgie@redhat.com>

### CODE REVIEW

**Comment by gouthamve** [comment]
I think we took this code from the etcd codebase. Not sure if changing the headers is the right thing to do here.

**Comment by krasi-georgiev** [comment]
good point, 
maybe @juliusv can comment on that?

**Comment by juliusv** [comment]
(or is keeping things the way they are fine?)

**Comment by swinslow** [comment]
Thanks @juliusv -- existing third-party copyright notices should be retained and should not be removed. 

If additional Prometheus content has been added to the files, then it should be fine to add an additional "Prometheus authors" notice -- but in any event the existing etcd statement should remain there too.

**Comment by juliusv** [comment]
@swinslow Thanks! :) I take it that everything should remain as is then, unless people have added stuff to them.

**Comment by swinslow** [comment]
Yes, exactly  :)  Thanks!

**Comment by swinslow** [comment]
One other thought -- if you're concerned that people in the future might think the "etcd" notice is a mistake and try to change it: you might consider moving files like this into a "third_party/etcd/" directory or something similar. That way it's clearer that they originated from a third party upstream project. Not critical here, since this is also Apache-2.0-licensed code, but just a thought.

**Comment by krasi-georgiev** [comment]
thanks for the info 
lets keep things as they are.

**Pull request closed without merging**
