### PR TITLE
Fix updating of NumTombstones in block.Delete(..)

### PR DESCRIPTION
**Pull request by codesome**
Fixes https://github.com/prometheus/tsdb/issues/384

Signed-off-by: Ganesh Vernekar <cs15btech11018@iith.ac.in>

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
I would say something like this would be a bit more clear and better to avoid races:

```

// TombstoneReader gives access to tombstone intervals by series reference.
type TombstoneReader interface {
	...
        // Total returns the total count of Tombstones.
	Total() uint64
}


func (t *memTombstones) Total() uint64 {
	t.mtx.RLock()
	defer t.mtx.RUnlock()

	var total uint64
	for _, intvs := range t.intvlGroups {
		total += uint64(len(intvs))
	}
	return total
}


func (pb *Block) Delete
....
pb.meta.Stats.NumTombstones = pb.tombstones.Total()

```

**Comment by codesome** [comment]
There wont be any race condition in the current change, but what you proposed looks good. I will add that function.

**Comment by krasi-georgiev** [comment]
LGTM 

ping @gouthamve

**Comment by krasi-georgiev** [comment]
Thanks!

**Pull request merged**
