### PR TITLE
return ErrOutOfOrderSample even on the same appender

### PR DESCRIPTION
**Pull request by krasi-georgiev**
supersedes: https://github.com/prometheus/tsdb/pull/258

ping @gouthamve 

any pointers how to run some good benchmarking?

I have tried `tsdb bench write` which shows very mixed results. 

Signed-off-by: Krasi Georgiev <kgeorgie@redhat.com>

### CODE REVIEW

**Comment by gouthamve** [comment]
Hmm, this fails for `Rollback`. Basically if there is `Rollback` the `lastTime` would be an invalid one.

**Comment by krasi-georgiev** [comment]
updated.

What worries is me that it brakes a test that specifically checks that adding an ooo sample doesn't cause an error as if this is desired behaviour.

https://github.com/prometheus/tsdb/blob/d1a6edae6f790fd286a3f5bf01274da9e5f53111/db_test.go#L351-L357

**Comment by krasi-georgiev** [comment]
ping @gouthamve

**Comment by krasi-georgiev** [comment]
@gouthamve any memories regarding https://github.com/prometheus/tsdb/pull/387#issuecomment-422594066 ?

**Comment by krasi-georgiev** [comment]
@fabxc do you remember why out of order sample are allowed to be added to the head?

**Comment by fabxc** [comment]
What do you mean? They aren't – hence the error.

**Comment by krasi-georgiev** [comment]
before the change in this PR adding  ooo samples don't return an error and they are just dropped.

there is even a test that specifically checks that adding ooo samples don't return an error.

https://github.com/prometheus/tsdb/blob/d1a6edae6f790fd286a3f5bf01274da9e5f53111/db_test.go#L351-L357

**Comment by fabxc** [comment]
Oh, that's what you mean. Yea, probably would be better to return some
PartialError that indicates how many samples have been dropped.
All callers would need to be adapted accordingly of course.

**Comment by krasi-georgiev** [comment]
@fabxc  ^

**Pull request closed without merging**
