### PR TITLE
remove opaque metrics

### PR DESCRIPTION
**Pull request by krasi-georgiev**
tsdb can save timestamps in any unit - sec,mils etc.
These metrics should be exposed by the library caller so they include
the unit suffix based on the unit used by the caller.

The api exposed enough details to allow this top be implemented by the
caller.

I will open a PR in Prometheus to add these there.

Signed-off-by: Krasi Georgiev <kgeorgie@redhat.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
These are still useful for general tsdb debugging, I'm not sure we should be removing them.

**Comment by krasi-georgiev** [comment]
if they can be be implemented by the caller you don't loose the debugging

**Comment by brian-brazil** [comment]
You do if they're not implemented. This is a perfectly fine metric for this library to expose, as it's a key internal bit of state.

**Comment by krasi-georgiev** [comment]
I am opening a PR to add these to Prometheus

**Comment by krasi-georgiev** [comment]
what is the point these will be exactly the same metrics?

**Comment by gouthamve** [comment]
As a user of the library, I would like to see these metrics being exposed without me having to write functions to get the start, end time for example.

We can maybe rename them to something else to avoid confusion with the prometheus metric.

**Comment by simonpasquier** [comment]
> We can maybe rename them to something else to avoid confusion with the prometheus metric.

Definitely yes to this.

**Comment by krasi-georgiev** [comment]
PR to add these to prometheus https://github.com/prometheus/prometheus/pull/4888

@gouthamve 	any suggestions about renaming these to be relevant for what you need it in tsdb?

**Comment by krasi-georgiev** [comment]
seems that there is no better name than the current one so leaving as is with just some more text in the help.

ping @gouthamve , @brian-brazil

**Comment by brian-brazil** [comment]
:+1:

**Pull request merged**
