### PR TITLE
Handle a bunch of unchecked errors

### PR DESCRIPTION
**Pull request by juliusv**
As discovered by "gosec".

Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
There's also these two Sync/Close calls in the segment truncation code where I'm not sure if at least one of them should be checked too? (there are a bunch of unchecked `Close()` calls and the like in general, but mostly we cannot do anything when they fail)

**Comment by juliusv** [comment]
Meant to include link in the previous comment: https://github.com/prometheus/tsdb/blob/master/wal.go#L403-L404

**Comment by krasi-georgiev** [comment]
ping @juliusv

**Comment by juliusv** [comment]
@krasi-georgiev Currently traveling, but I think it should be fine to merge as is, and adding additional error logs for `Sync()` and `Close()` calls can still be done separately if people feel it's a good idea.

**Comment by krasi-georgiev** [comment]
Thanks!

**Pull request merged**
